# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmonbart <- function(xm, yv, xpm, tau, nu, lambda, alpha, mybeta, nd, burn, m, nm, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery) {
    .Call(`_monbart_cmonbart`, xm, yv, xpm, tau, nu, lambda, alpha, mybeta, nd, burn, m, nm, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery)
}

cpmonbart <- function(xm, yv, xpm, tau, alpha, mybeta, binaryOffset, nd, burn, m, nm, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery) {
    .Call(`_monbart_cpmonbart`, xm, yv, xpm, tau, alpha, mybeta, binaryOffset, nd, burn, m, nm, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery)
}

rcpp_hello_world <- function() {
    .Call(`_monbart_rcpp_hello_world`)
}

